//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.22 at 08:56:22 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://mx.itesm.todolist.domain.imb")
package imb.domain.todolist.itesm.mx;
